name: Security Scanning & Dependency Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security-scan:
    name: Security & Dependency Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety bandit semgrep

      - name: Run Bandit security scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . -f txt
        continue-on-error: true

      - name: Run Safety check for known vulnerabilities
        run: |
          safety check --json > safety-report.json || true
          safety check
        continue-on-error: true

      - name: Run Semgrep for code patterns
        run: |
          semgrep --config=p/security-audit --json -o semgrep-report.json || true
        continue-on-error: true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: |
            bandit-report.sarif
            semgrep-report.sarif
        continue-on-error: true

      - name: Create security report summary
        if: always()
        run: |
          echo "## 🔒 Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Bandit Security Audit" >> $GITHUB_STEP_SUMMARY
          bandit -r . -f txt >> $GITHUB_STEP_SUMMARY 2>&1 || echo "✅ Bandit check passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Dependency Vulnerabilities" >> $GITHUB_STEP_SUMMARY
          safety check >> $GITHUB_STEP_SUMMARY 2>&1 || echo "✅ No known vulnerabilities" >> $GITHUB_STEP_SUMMARY

  dependency-audit:
    name: Pip Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit
        continue-on-error: true

  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'python'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: Secret Detection
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install secret scanning tools
        run: |
          pip install detect-secrets truffleHog3

      - name: Run detect-secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline || true
        continue-on-error: true

      - name: Run truffleHog
        run: |
          pip install truffleHog3
          truffleHog3 -r . -o json > truffleHog-report.json || true
        continue-on-error: true

  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-licenses

      - name: Check licenses
        run: pip-licenses --format=markdown --output-file=LICENSES.md
        continue-on-error: true

      - name: Display license report
        run: cat LICENSES.md

  report-summary:
    name: Security Report Summary
    runs-on: ubuntu-latest
    needs: [security-scan, dependency-audit, codeql-analysis, secret-scanning, license-check]
    if: always()
    permissions:
      contents: read
      
    steps:
      - name: Report completion
        run: |
          echo "✅ Security scanning pipeline completed"
          echo ""
          echo "Reports generated:"
          echo "- Bandit security audit"
          echo "- Safety dependency check"
          echo "- Semgrep code patterns"
          echo "- CodeQL analysis"
          echo "- Secret detection"
          echo "- License compliance"
          echo ""
          echo "Check GitHub Security tab for detailed results"
